# Coolify Docker Compose für SAMEBI Backend
# Nur PostgREST - PostgreSQL läuft separat in Coolify

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PGRST_DB_URI=${PGRST_DB_URI}
      - PGRST_DB_SCHEMAS=${PGRST_DB_SCHEMAS}
      - PGRST_DB_ANON_ROLE=${PGRST_DB_ANON_ROLE}
      - PGRST_JWT_SECRET=${PGRST_JWT_SECRET}
    ports:
      - "3000:3000"
    restart: unless-stopped
